### ISSUE TITLE
Hash mismatch of node #xxx and its children

### ISSUE THREAD

**Issue by jiqiang90** [zmitton/merkle-mountain-range#9]
Hi, 

I have a mmr set wordSize to 32. 

It works fine when generate mmr value, but when I'm using `.get()` to node value, it showing this error 

```
Hash mismatch of node #xxx and its children
```

```
// degistValue : this.digest(leftValue, rightValue);
<Buffer 46 65 4c cc ba 5d 40 0a a8 79 c9 7a 61 11 91 b4 03 51 49 0e c7 41 92 20 fb d3 62 85 69 58 05 28 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 14 more bytes>
// currentValue:  this is read from filebasedDb
<Buffer 46 65 4c cc ba 5d 40 0a a8 79 c9 7a 61 11 91 b4 03 51 49 0e c7 41 92 20 fb d3 62 85 69 58 05 28>
```

I'm using `keccak256FlyHash`, and I found it was failed due to output been added additional 32 bytes of `difficultySumBytes`.
https://github.com/zmitton/merkle-mountain-range/blob/2a3ce68ca5ad1dc27d8403d1a73213051a28a538/src/digests.js#L19

Can you explain what is this `difficultySumBytes` for ? also Any suggestion to resolve this issue?

**Comment by zmitton** [comment]
`difficultysumbytes`  is from the flyclient spec. each commitment hash must include the difficulty up the tree. Im not sure exactly the issue but if you dont need the difficulty sums (if you are not implementing flyclient), you can possibly fix it by using `keccak()` instead of `keccak256FlyHash()`. It should be the same thing without the sum.


from the flyclient paper the sum is supposed to verify the difficulty at each node is the sum of its children. 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/6954889/168680454-c0cfb164-ff5c-4f00-b759-6d9c4654f83f.png">

**Comment by zmitton** [comment]
if this is not what you need, please describe the issue in more detail and i will try to help

**Comment by jiqiang90** [comment]
@zmitton Thank you, this is helpful. I think the ticket can closes now, we changed to use `keccak()` it works well.
